version: "3.8"

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  backend:
    build: ./backend/
    volumes:
      - ./backend/:/app
    ports:
      - "3001:3000"
    depends_on:
        - db
    links:
        - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/app
    ports:
      - "80:3000"
    depends_on:
        - backend
